### ISSUE TITLE
Redirect to https://github.com/wikimedia/purtle

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/purtle#4]
Please redirect this confusing mirror to https://github.com/wikimedia/purtle.

**Comment by brightbyte** [comment]
Note sure how redirecting/transferring would work in this case. It seems it would have to be done by someone with admin rights in the wmde and wikimedia organizations.

**Comment by tobijat** [comment]
I don't think we can just redirect to a different organization's repository..

**Comment by tobijat** [comment]
Yeah, I just realized that it is possible (we're doing it for https://github.com/wmde/WikidataBuildResources/) but I don't know how to do it. I think what @brightbyte  sais, it needs to be done by an admin in the WMDE and Wikimedia organization.

**Comment by tobijat** [comment]
@filbertkm? Are you able to do this?

**Comment by brightbyte** [comment]
Relevant: https://help.github.com/articles/transferring-a-repository/

**Comment by brightbyte** [comment]
The thing is: we don't really want to transfer it. wikimedia/purtle already exists. It's a clone from gerrit. Maybe it doesn't matter. But maybe it does.

**Comment by brightbyte** [comment]
Anyway: this repo has existed for like 4 days. I don't think anyone or anything is relying on it yet. If redirecting isn't trivial, it's not worth the trouble imho.

**Comment by thiemowmde** [comment]
As said, when possible. Please delete it when it's not possible.

**Comment by filbertkm** [comment]
@tobijat I have no idea how this was done for WikidataBuildResources. Maybe @JanZerebecki knows?  

In this case, I don't see a problem with deleting the repo since it was used so briefly.

**Comment by JanZerebecki** [comment]
Ok done.
